target: "Usage_kWh"
datetime_col: "date"
categorical_cols: ["WeekStatus", "Day_of_week", "Load_Type"]
numeric_cols:
  - "Lagging_Current_Reactive.Power_kVarh"
  - "Leading_Current_Reactive_Power_kVarh"
  - "CO2(tCO2)"
  - "Lagging_Current_Power_Factor"
  - "Leading_Current_Power_Factor"
  - "NSM"
# optional: add engineered features later
outlier_cap:
  method: "iqr"
  factor: 3.0

